// Generated by the moc meta-object compiler

#include "core.h"

static const char signal_names[] = "signal1;";
static const char slots_names[] = "slot1;";

MetaObject Object::meta = { signal_names, slots_names };

void Object::sig1()
{
	MetaObject::active(this, 0);
}

void Object::metacall(int idx)
{
	switch (idx) {
	case 0:
		slot1();
		break;
	default:
		break;
	};
}